apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-node
  template:
    metadata:
      labels:
        app: sample-node
    spec:
      containers:
        - name: sample-node
          image: samplenew
          ports:
          - containerPort: 3000
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: sample-srv
spec:
  type: NodePort
  selector:
    app: sample-node
  ports:
    - name: sample-port
      protocol: TCP
      port: 8080
      targetPort: 3000

